// NOTE: isFactTopic is no longer used here. contentIntent is now explicitly
// generated by the LLM for each angle, replacing regex-based inference.

interface NichePromptBase {
  channelName: string;
  memory?: {
    tone?: string;
    avoidPatterns?: string[];
    style?: string;
  };
}

interface DiscoverParams extends NichePromptBase {
  mode: 'discover';
}

interface ExploreParams extends NichePromptBase {
  mode: 'explore';
  topic: string;
}

interface DirectRefineParams extends NichePromptBase {
  mode: 'direct';
  topic: string;
}

interface RegenerateMoreParams extends NichePromptBase {
  existingTitles: string[];
  intent: 'more_viral' | 'more_niche' | 'more_monetizable' | 'more_unconventional';
  topic?: string;
}

export type NicheGenerationParams = DiscoverParams | ExploreParams | DirectRefineParams;

// ─── Shared Fragments ─────────────────────────────────────────

function buildMemoryContext(memory?: NichePromptBase['memory']): string {
  if (!memory) return '';
  return `
CHANNEL MEMORY (respect these preferences):
- Tone: ${memory.tone ?? 'Not set'}
- Style: ${memory.style ?? 'Not set'}
- Patterns to avoid: ${memory.avoidPatterns?.join(', ') ?? 'None set'}
`;
}

const SCORING_CRITERIA = '';

const ANTI_PATTERNS = `
ANTI-PATTERNS (never do these):
- No generic self-help niches ("personal growth", "motivation", "mindset")
- No oversaturated fitness/wealth/dating advice
- No niches that require the creator to be a recognized expert
- No niches defined by format ("carousel tips", "reels hacks")
- No niches that are just "X for Y demographic" repackaging
`;

const WRITING_RULES = `
WRITING STYLE RULES:
- Titles should be 2-4 words, sharp, memorable
- Descriptions should be 2-3 sentences that paint a vivid picture of the content angle
- Rationale should explain WHY this niche works right now, not just what it is
- Be specific — "Digital Minimalism" is better than "Technology"
- Each niche should feel like a distinct editorial voice, not just a topic
`;

// ─── Discover Mode ────────────────────────────────────────────

function buildDiscoverPrompt(params: DiscoverParams): string {
  return `You are an elite Instagram content strategist specializing in niche discovery.

TASK: Generate exactly 5 niche options for a new Instagram channel.

LANGUAGE: All output must be in English.

No specific topic provided. Explore high-opportunity niches in the current creator landscape that have low competition and high virality potential.

${buildMemoryContext(params.memory)}
${SCORING_CRITERIA}
${WRITING_RULES}
${ANTI_PATTERNS}

CONTENT INTENT — REQUIRED FOR EVERY OPTION:
Each option MUST include a "contentIntent" field with one of these exact values:
- "evergreen_fact": The angle is about timeless, verifiable facts (animal facts, science facts, history facts, myth-busting, mechanisms, comparisons). Content is educational and true regardless of when it's read.
- "story": The angle is narrative-driven — stories, profiles, emotional journeys, case studies.
- "general": Everything else — opinions, tips, trends, commentary, mixed content.

Choose the intent that BEST describes what content this angle would produce.

EXACT JSON SCHEMA (follow precisely):
{
  "options": [
    {
      "title": "string",
      "description": "string",
      "rationale": "string",
      "contentIntent": "evergreen_fact" | "story" | "general"
    }
  ]
}

CRITICAL: contentIntent must be one of the three exact string values. Return exactly 5 options.`;
}

// ─── Explore Mode ─────────────────────────────────────────────

function buildExplorePrompt(params: ExploreParams): string {
  return `You are an elite Instagram content strategist specializing in finding sharp content angles within a SPECIFIC topic chosen by the user.

TASK: Generate exactly 7 niche angle options strictly within the topic: "${params.topic}"

LANGUAGE: All output must be in English.

════════════════════════════════════════════════════════
HARD CONSTRAINT — READ THIS CAREFULLY:

The user's topic is: "${params.topic}"

Every single output MUST be clearly, obviously, and directly about "${params.topic}".

- DO NOT generate angles about unrelated domains.
- DO NOT drift into adjacent topics unless they directly involve "${params.topic}".
- DO NOT generate generic content strategy angles that could apply to any topic.
- If an output is not immediately recognizable as being about "${params.topic}", it is INVALID.

A reader should be able to look at each title and description and instantly say: "Yes, this is about ${params.topic}."
════════════════════════════════════════════════════════

Your job is to find sharp, specific, opinionated content angles WITHIN the world of "${params.topic}". Not synonyms, not generic sub-categories — distinct editorial voices that could sustain 30+ days of posts.

════════════════════════════════════════════════════════
CONTENT INTENT — CRITICAL:

For EACH angle, you MUST determine its contentIntent. This is NOT optional.

- "evergreen_fact": The angle is about timeless, verifiable facts (animal facts, science facts, history facts, myth-busting, mechanisms, comparisons, "facts that sound fake", ranked lists by measurable criteria, biological mechanisms, counterintuitive truths). Content is educational and true regardless of when it's read.
- "story": The angle is narrative-driven — stories, profiles, emotional journeys, case studies.
- "general": Everything else — opinions, tips, trends, commentary, mixed content.

If an angle is about weird facts, surprising truths, hidden mechanisms, misconceptions, or educational content about "${params.topic}", it MUST have contentIntent = "evergreen_fact".

Angles with contentIntent = "evergreen_fact" have ADDITIONAL constraints:
- GOOD: myth-busting, hidden mechanisms, extreme comparisons, weird/surprising facts, misconceptions debunked
- BANNED: Story/narrative angles, emotional/cute/sentimental angles, news/event angles, editorial/opinion angles, person-led angles
- Each title should make it clear this is a FACT channel, not a story/news/editorial channel.
════════════════════════════════════════════════════════
GOOD EXAMPLE (if the topic were "greek mythology"):
- "Greek myths the movies got completely wrong" — debunking, educational, visual
- "The psychological horror in Greek myths" — dark reframes, pattern analysis
- "Greek gods ranked by how unhinged they were" — entertainment, lists, hot takes
- "Greek mythology facts that sound fake but aren't" — curiosity gap, shareable
- "What Greek myths reveal about modern relationships" — modern relevance, relatable
- "The most brutal punishments in Greek mythology" — shock value, storytelling
- "Greek myths every adult should actually know" — educational, anti-ignorance

BAD EXAMPLE (if the topic were "greek mythology"):
- "AI shortcuts for content creators" — COMPLETELY UNRELATED, INVALID
- "Content creation tips" — not about the topic at all
- "Digital storytelling" — too vague, not anchored to the topic
- "History facts" — too broad, not specific to the topic

${buildMemoryContext(params.memory)}
${SCORING_CRITERIA}
${WRITING_RULES}
${ANTI_PATTERNS}

FINAL REMINDER: Every option must be unmistakably about "${params.topic}". No exceptions. Every angle MUST have the correct contentIntent — fact-based angles MUST be "evergreen_fact".

EXACT JSON SCHEMA (follow precisely):
{
  "options": [
    {
      "title": "string",
      "description": "string",
      "rationale": "string",
      "contentIntent": "evergreen_fact" | "story" | "general"
    }
  ]
}

CRITICAL: contentIntent must be one of the three exact string values. Return exactly 7 options.`;
}

// ─── Direct Topic Refinement ──────────────────────────────────

function buildDirectRefinePrompt(params: DirectRefineParams): string {
  return `You are an elite Instagram content strategist specializing in sharpening content positioning.

TASK: The user already knows their topic: "${params.topic}". Generate exactly 5 sharper angles or positioning variants for this exact topic for a new Instagram channel.

LANGUAGE: All output must be in English.

IMPORTANT: The user has committed to this topic. Do NOT suggest completely different topics. Instead, generate 5 different editorial angles or positioning takes ON THIS SAME TOPIC.

Each option should represent a different voice, perspective, or framing of "${params.topic}" — not a different topic.

Example: If the topic is "AI tools for creators":
- Option 1: "The brutally honest AI toolkit" — no hype, only tools that actually work after 30 days
- Option 2: "AI automation confessions" — exposing the messy reality behind polished AI workflows
- Option 3: "AI tools your favorite creators secretly use" — insider access, discovery angle
- Option 4: "AI tools for creators who hate AI" — contrarian, skeptic-friendly entry point
- Option 5: "The $0 AI stack" — free tools only, anti-premium positioning

${buildMemoryContext(params.memory)}
${SCORING_CRITERIA}
${WRITING_RULES}

CONTENT INTENT — REQUIRED FOR EVERY OPTION:
Each option MUST include a "contentIntent" field with one of these exact values:
- "evergreen_fact": The angle is about timeless, verifiable facts. Content is educational and true regardless of when it's read.
- "story": The angle is narrative-driven — stories, profiles, emotional journeys, case studies.
- "general": Everything else — opinions, tips, trends, commentary, mixed content.

EXACT JSON SCHEMA (follow precisely):
{
  "options": [
    {
      "title": "string",
      "description": "string",
      "rationale": "string",
      "contentIntent": "evergreen_fact" | "story" | "general"
    }
  ]
}

CRITICAL: contentIntent must be one of the three exact string values. Return exactly 5 options.`;
}

// ─── Regenerate More ──────────────────────────────────────────

export function buildRegenerateMorePrompt(params: RegenerateMoreParams): string {
  const intentInstructions: Record<typeof params.intent, string> = {
    more_viral: `Generate niches with MAXIMUM viral potential. Prioritize:
- Topics that trigger strong emotional reactions (outrage, surprise, relief)
- Content that people screenshot and share in DMs
- Hooks that create curiosity gaps impossible to ignore
- Universal relatability — the widest possible audience overlap`,

    more_niche: `Generate niches that are ULTRA-SPECIFIC and underserved. Prioritize:
- Micro-communities with passionate but underserved audiences
- Topics where you can become THE voice within weeks
- Angles too specific for big creators to bother with
- Low competition scores — find the gaps everyone missed`,

    more_monetizable: `Generate niches with CLEAR revenue paths. Prioritize:
- Topics where the audience has spending power and intent
- Natural product/service tie-ins (courses, tools, consulting)
- B2B adjacent angles where businesses pay for expertise
- Niches where trust converts directly to transactions`,

    more_unconventional: `Generate niches that are WEIRD, UNEXPECTED, and contrarian. Prioritize:
- Angles nobody else would think to create content about
- Counter-intuitive takes on popular spaces
- Topics that make people say "wait, that's a thing?"
- Content that breaks format expectations entirely`,
  };

  return `You are an elite Instagram content strategist. The user wants MORE niche options with a specific intent.

TASK: Generate exactly 5 NEW niche options for a new Instagram channel.

LANGUAGE: All output must be in English.

INTENT: ${intentInstructions[params.intent]}

${params.topic ? `The user is exploring the area of: "${params.topic}". Stay within or adjacent to this space.` : 'No specific topic constraint — explore freely.'}

EXISTING OPTIONS TO AVOID (do NOT repeat or rephrase these):
${params.existingTitles.map((t) => `- ${t}`).join('\n')}

${buildMemoryContext(params.memory)}
${SCORING_CRITERIA}
${WRITING_RULES}
${ANTI_PATTERNS}

CONTENT INTENT — REQUIRED FOR EVERY OPTION:
Each option MUST include a "contentIntent" field with one of these exact values:
- "evergreen_fact": The angle is about timeless, verifiable facts. Content is educational and true regardless of when it's read.
- "story": The angle is narrative-driven — stories, profiles, emotional journeys, case studies.
- "general": Everything else — opinions, tips, trends, commentary, mixed content.

EXACT JSON SCHEMA (follow precisely):
{
  "options": [
    {
      "title": "string",
      "description": "string",
      "rationale": "string",
      "contentIntent": "evergreen_fact" | "story" | "general"
    }
  ]
}

CRITICAL: contentIntent must be one of the three exact string values. Return exactly 5 options.`;
}

// ─── Main Entry Point ─────────────────────────────────────────

export function buildNicheGenerationPrompt(params: NicheGenerationParams): string {
  switch (params.mode) {
    case 'discover':
      return buildDiscoverPrompt(params);
    case 'explore':
      return buildExplorePrompt(params);
    case 'direct':
      return buildDirectRefinePrompt(params);
  }
}
